// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDECW6JTwF6UF5KfmJTojIW6s2c6PWAv44',
    appId: '1:378543758997:web:f88b4b48574a8c6e79859c',
    messagingSenderId: '378543758997',
    projectId: 'appdatabase-25265',
    authDomain: 'appdatabase-25265.firebaseapp.com',
    storageBucket: 'appdatabase-25265.appspot.com',
    measurementId: 'G-N6CZXPXDXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy7hA8gk1arrzodaKfc4L1BevmlJ_qyMU',
    appId: '1:378543758997:android:8269da628ace57ef79859c',
    messagingSenderId: '378543758997',
    projectId: 'appdatabase-25265',
    storageBucket: 'appdatabase-25265.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj8tAPdNmYEXcrRV2t8-h3WmbLg7GhPv4',
    appId: '1:378543758997:ios:e5ebb4900a3fb10079859c',
    messagingSenderId: '378543758997',
    projectId: 'appdatabase-25265',
    storageBucket: 'appdatabase-25265.appspot.com',
    iosBundleId: 'com.example.pavliText',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj8tAPdNmYEXcrRV2t8-h3WmbLg7GhPv4',
    appId: '1:378543758997:ios:739d0f1d2d8ddb5d79859c',
    messagingSenderId: '378543758997',
    projectId: 'appdatabase-25265',
    storageBucket: 'appdatabase-25265.appspot.com',
    iosBundleId: 'com.example.pavliText.RunnerTests',
  );
}
